In [1608]:
import pandas as pd

In [1609]:
import numpy as np

In [1610]:
dataset = pd.read_csv('train.csv')

In [1611]:
dataset.head(20)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,conditions Sunny,High,2,Snack,motorcycle,0,No,Urban,(min) 24
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,conditions Stormy,Jam,2,Snack,scooter,1,No,Metropolitian,(min) 33
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,8:30:00,8:45:00,conditions Sandstorms,Low,0,Drinks,motorcycle,1,No,Urban,(min) 26
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,5/4/2022,18:00:00,18:10:00,conditions Sunny,Medium,0,Buffet,motorcycle,1,No,Metropolitian,(min) 21
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,conditions Cloudy,High,1,Snack,scooter,1,No,Metropolitian,(min) 30
5,0x9bb4,HYDRES09DEL03,22,4.8,17.431668,78.408321,17.461668,78.438321,11/3/2022,21:20:00,21:30:00,conditions Cloudy,Jam,0,Buffet,motorcycle,1,No,Urban,(min) 26
6,0x95b4,RANCHIRES15DEL01,33,4.7,23.369746,85.339820,23.479746,85.449820,4/3/2022,19:15:00,19:30:00,conditions Fog,Jam,1,Meal,scooter,1,No,Metropolitian,(min) 40
7,0x9eb2,MYSRES15DEL02,35,4.6,12.352058,76.606650,12.482058,76.736650,14-03-2022,17:25:00,17:30:00,conditions Cloudy,Medium,2,Meal,motorcycle,1,No,Metropolitian,(min) 32
8,0x1102,HYDRES05DEL02,22,4.8,17.433809,78.386744,17.563809,78.516744,20-03-2022,20:55:00,21:05:00,conditions Stormy,Jam,0,Buffet,motorcycle,1,No,Metropolitian,(min) 34
9,0xcdcd,DEHRES17DEL01,36,4.2,30.327968,78.046106,30.397968,78.116106,12/2/2022,21:55:00,22:10:00,conditions Fog,Jam,2,Snack,motorcycle,3,No,Metropolitian,(min) 46
10,0xd987,KOCRES16DEL01,21,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55:00,15:05:00,conditions Stormy,High,1,Meal,motorcycle,1,No,Metropolitian,(min) 23
11,0x2784,PUNERES13DEL03,23,4.7,18.562450,73.916619,18.652450,74.006619,4/3/2022,17:30:00,17:40:00,conditions Sandstorms,Medium,1,Drinks,scooter,1,No,Metropolitian,(min) 21
12,0xc8b6,LUDHRES15DEL02,34,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,9:20:00,9:30:00,conditions Sandstorms,Low,0,Buffet,motorcycle,0,No,Metropolitian,(min) 20
13,0xdb64,KNPRES14DEL02,24,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50:00,20:05:00,conditions Fog,Jam,1,Snack,scooter,1,No,Metropolitian,(min) 41
14,0x3af3,MUMRES15DEL03,29,4.5,19.176269,72.836721,19.266269,72.926721,2/4/2022,20:25:00,20:35:00,conditions Sandstorms,Jam,2,Buffet,electric_scooter,1,No,Metropolitian,(min) 20
15,0x3aab,MYSRES01DEL01,35,4,12.311072,76.654878,12.351072,76.694878,1/3/2022,14:55:00,15:10:00,conditions Windy,High,1,Meal,scooter,1,No,Metropolitian,(min) 33
16,0x689b,PUNERES20DEL01,33,4.2,18.592718,73.773572,18.702718,73.883572,16-03-2022,20:30:00,20:40:00,conditions Sandstorms,Jam,2,Snack,motorcycle,1,No,Metropolitian,(min) 40
17,0x6f67,HYDRES14DEL01,34,4.9,17.426228,78.407495,17.496228,78.477495,20-03-2022,20:40:00,20:50:00,conditions Cloudy,Jam,0,Snack,motorcycle,NaN,No,Metropolitian,(min) 41
18,0xc9cf,KOLRES15DEL03,21,4.7,22.552672,88.352885,22.582672,88.382885,15-02-2022,21:15:00,21:30:00,conditions Windy,Jam,0,Meal,motorcycle,1,No,Urban,(min) 15
19,0x36b8,PUNERES19DEL02,25,4.1,18.563934,73.915367,18.643935,73.995367,16-03-2022,20:20:00,20:25:00,conditions Sandstorms,Jam,0,Snack,motorcycle,2,No,Metropolitian,(min) 36

In [1612]:
dataset.tail(20)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
45573,0x6997,MUMRES20DEL02,26,4.5,19.103249,72.846749,19.183249,72.926749,18-03-2022,20:40:00,20:45:00,conditions Windy,Jam,1,Snack,motorcycle,1,No,Metropolitian,(min) 17
45574,0x90c5,MUMRES20DEL03,21,4.8,19.103249,72.846749,19.133249,72.876749,19-03-2022,22:15:00,22:20:00,conditions Sunny,Low,2,Drinks,motorcycle,0,No,Metropolitian,(min) 22
45575,0x91d5,HYDRES03DEL03,34,4.9,17.422819,78.449578,17.482819,78.509578,24-03-2022,21:45:00,22:00:00,conditions Stormy,Jam,1,Meal,motorcycle,1,No,Metropolitian,(min) 28
45576,0x2bed,RANCHIRES02DEL02,34,4.2,0.000000,0.000000,0.130000,0.130000,4/4/2022,17:25:00,17:30:00,conditions Stormy,Medium,0,Drinks,motorcycle,3,No,Urban,(min) 48
45577,0x373f,VADRES12DEL03,25,4.7,0.000000,0.000000,0.090000,0.090000,29-03-2022,22:10:00,22:15:00,conditions Cloudy,Low,0,Buffet,motorcycle,1,No,Metropolitian,(min) 21
45578,0x5640,COIMBRES03DEL02,30,4.9,11.025083,77.015393,11.045083,77.035393,11/3/2022,10:25:00,10:40:00,conditions Windy,Low,1,Snack,motorcycle,1,No,Metropolitian,(min) 26
45579,0xdf1d,BHPRES19DEL02,32,4.6,0.000000,0.000000,0.050000,0.050000,15-02-2022,18:10:00,18:20:00,conditions Stormy,Medium,2,Drinks,scooter,1,No,Metropolitian,(min) 27
45580,0xbb2b,MYSRES08DEL02,34,4.9,12.297954,76.665169,12.317954,76.685169,5/4/2022,9:10:00,9:15:00,conditions Sandstorms,Low,1,Snack,scooter,1,No,NaN,(min) 26
45581,0x51f0,SURRES02DEL03,20,4.9,21.186608,72.794136,21.216608,72.824136,3/3/2022,20:25:00,20:40:00,conditions Sandstorms,Jam,2,Drinks,motorcycle,1,No,Urban,(min) 18
45582,0x59ae,PUNERES13DEL02,30,4.6,18.562450,73.916619,18.582450,73.936619,1/4/2022,9:00:00,9:15:00,conditions Cloudy,Low,0,Meal,motorcycle,0,No,Metropolitian,(min) 20
45583,0x5193,MYSRES13DEL02,36,4.8,12.310972,76.659264,12.440972,76.789264,18-03-2022,21:10:00,21:20:00,conditions Sunny,Jam,2,Drinks,electric_scooter,1,No,Urban,(min) 29
45584,0xa333,CHENRES08DEL02,37,4.8,13.022394,80.242439,13.042394,80.262439,5/4/2022,9:35:00,9:50:00,conditions Sandstorms,Low,2,Drinks,electric_scooter,0,No,Metropolitian,(min) 20
45585,0xc9ab,KNPRES03DEL01,30,4.2,26.469003,80.316344,26.539003,80.386344,14-02-2022,18:10:00,18:25:00,conditions Cloudy,Medium,1,Snack,motorcycle,2,Yes,Metropolitian,(min) 42
45586,0x4e21,BANGRES16DEL03,28,4.9,13.029198,77.570997,13.059198,77.600997,30-03-2022,21:55:00,22:00:00,conditions Sandstorms,Jam,1,Meal,scooter,1,No,Metropolitian,(min) 29
45587,0x1178,RANCHIRES16DEL01,35,4.2,23.371292,85.327872,23.481292,85.437872,8/3/2022,21:45:00,21:55:00,conditions Windy,Jam,2,Drinks,motorcycle,1,No,Metropolitian,(min) 33
45588,0x7c09,JAPRES04DEL01,30,4.8,26.902328,75.794257,26.912328,75.804257,24-03-2022,11:35:00,11:45:00,conditions Windy,High,1,Meal,motorcycle,0,No,Metropolitian,(min) 32
45589,0xd641,AGRRES16DEL01,21,4.6,0.000000,0.000000,0.070000,0.070000,16-02-2022,19:55:00,20:10:00,conditions Windy,Jam,0,Buffet,motorcycle,1,No,Metropolitian,(min) 36
45590,0x4f8d,CHENRES08DEL03,30,4.9,13.022394,80.242439,13.052394,80.272439,11/3/2022,23:50:00,0:05:00,conditions Cloudy,Low,1,Drinks,scooter,0,No,Metropolitian,(min) 16
45591,0x5eee,COIMBRES11DEL01,20,4.7,11.001753,76.986241,11.041753,77.026241,7/3/2022,13:35:00,13:40:00,conditions Cloudy,High,0,Snack,motorcycle,1,No,Metropolitian,(min) 26
45592,0x5fb2,RANCHIRES09DEL02,23,4.9,23.351058,85.325731,23.431058,85.405731,2/3/2022,17:10:00,17:15:00,conditions Fog,Medium,2,Snack,scooter,1,No,Metropolitian,(min) 36

In [1613]:
dataset.sample(20)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
34277,0xbb54,PUNERES09DEL01,33,4.6,18.536562,73.896485,18.646562,74.006485,4/3/2022,21:35:00,21:40:00,conditions Fog,Jam,2,Drinks,scooter,2,No,Metropolitian,(min) 41
29204,0x9614,MUMRES11DEL01,32,4.8,18.994237,72.825553,19.064237,72.895553,2/4/2022,17:50:00,17:55:00,conditions Sunny,Medium,1,Drinks,motorcycle,1,No,Metropolitian,(min) 19
45022,0xb051,CHENRES19DEL03,30,4.8,12.986047,80.218114,13.076047,80.308114,4/3/2022,20:35:00,20:40:00,conditions Sunny,Jam,2,Meal,scooter,1,No,Metropolitian,(min) 28
5630,0x934,CHENRES09DEL01,NaN,NaN,13.044694,80.261470,13.054694,80.271470,7/3/2022,NaN,8:25:00,conditions Stormy,Low,0,Meal,motorcycle,1,No,Urban,(min) 25
39387,0xbe4c,BANGRES17DEL01,34,4.9,12.972532,77.608179,13.082532,77.718179,4/4/2022,18:30:00,18:35:00,conditions Sunny,Medium,0,Snack,motorcycle,1,No,Metropolitian,(min) 35
8896,0x47fc,CHENRES09DEL01,39,4.2,13.044694,80.261470,13.054694,80.271470,9/3/2022,11:20:00,11:30:00,conditions Stormy,High,2,Meal,electric_scooter,1,No,Metropolitian,(min) 33
37437,0x962b,INDORES11DEL02,31,4.7,22.751234,75.889490,22.771234,75.909490,1/4/2022,9:45:00,10:00:00,conditions Cloudy,Low,1,Buffet,motorcycle,0,No,Metropolitian,(min) 17
28256,0xacc,MYSRES06DEL01,24,4.7,12.323994,76.626167,12.433994,76.736167,29-03-2022,23:55:00,0:10:00,conditions Cloudy,Low,0,Snack,motorcycle,0,No,Metropolitian,(min) 24
31422,0xc352,DEHRES08DEL03,21,4.5,30.359722,78.067079,30.389722,78.097079,17-02-2022,17:40:00,17:50:00,conditions Cloudy,Medium,1,Buffet,motorcycle,1,No,Urban,(min) 13
29712,0x2956,CHENRES15DEL01,NaN,NaN,13.026286,80.275235,13.036286,80.285235,3/3/2022,NaN,11:35:00,conditions NaN,NaN,3,Drinks,motorcycle,1,No,Metropolitian,(min) 29
2054,0x73fc,COIMBRES010DEL02,35,4.9,11.003008,76.975440,11.133009,77.105440,4/4/2022,22:40:00,22:45:00,conditions Fog,Low,1,Buffet,scooter,1,No,Metropolitian,(min) 25
23839,0x5f8,MYSRES13DEL01,NaN,NaN,-12.310972,76.659264,12.420972,76.769264,14-03-2022,NaN,23:05:00,conditions Stormy,Low,0,Snack,motorcycle,0,No,Metropolitian,(min) 25
36743,0x7033,PUNERES20DEL02,29,4.8,18.592718,73.773572,18.642718,73.823572,13-03-2022,18:10:00,18:25:00,conditions Stormy,Medium,1,Drinks,motorcycle,1,No,Metropolitian,(min) 21
40493,0x7bac,BANGRES20DEL03,30,4.8,12.972161,77.596014,13.002161,77.626014,5/3/2022,17:25:00,17:40:00,conditions Cloudy,Medium,0,Drinks,motorcycle,0,No,Metropolitian,(min) 27
5833,0x5d33,BANGRES010DEL01,31,4.3,12.933298,77.614293,13.043298,77.724293,10/3/2022,17:25:00,17:35:00,conditions Sunny,Medium,0,Snack,motorcycle,1,No,Metropolitian,(min) 37
19001,0x7548,VADRES20DEL03,34,4.2,22.311358,73.164798,22.341358,73.194798,7/3/2022,17:25:00,17:40:00,conditions Sandstorms,Medium,2,Buffet,motorcycle,1,No,Metropolitian,(min) 33
13145,0xc7aa,AURGRES14DEL03,29,5,19.875016,75.322405,19.905016,75.352405,17-02-2022,17:15:00,17:30:00,conditions Cloudy,Medium,0,Buffet,motorcycle,1,No,Metropolitian,(min) 24
45100,0x505a,HYDRES02DEL03,24,4.6,17.412330,78.449654,17.472330,78.509654,26-03-2022,17:55:00,18:10:00,conditions Sandstorms,Medium,1,Buffet,scooter,1,No,Metropolitian,(min) 21
38029,0x6e92,CHENRES02DEL03,27,4.9,13.086438,80.220672,13.116438,80.250672,3/4/2022,17:15:00,17:20:00,conditions Sandstorms,Medium,2,Snack,motorcycle,0,No,Metropolitian,(min) 25
37050,0x807a,BANGRES15DEL02,38,3.5,12.975377,77.696664,13.055377,77.776664,6/3/2022,20:20:00,20:30:00,conditions Windy,Jam,2,Meal,scooter,2,No,Metropolitian,(min) 32

In [1614]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  str
 1   Delivery_person_ID           45593 non-null  str
 2   Delivery_person_Age          45593 non-null  str
 3   Delivery_person_Ratings      45593 non-null  str
 4   Restaurant_latitude          45593 non-null  float64
 5   Restaurant_longitude         45593 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Order_Date                   45593 non-null  str
 9   Time_Orderd                  45593 non-null  str
 10  Time_Order_picked            45593 non-null  str
 11  Weatherconditions            45593 non-null  str
 12  Road_traffic_density         45593 non-null  str
 13  Vehicle_condition            45593 non-null  int64
 14  Type_of_order                45593 non-null  str
 15  Type_of_vehicle              45593 non-null  str
 16  multiple_deliveries          45593 non-null  str
 17  Festival                     45593 non-null  str
 18  City                         45593 non-null  str
 19  Time_taken(min)              45593 non-null  str
dtypes: float64(4), int64(1), str(15)
memory usage: 7.0 MB

In [1615]:
dataset.describe()

,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Vehicle_condition
count,45593.000000,45593.000000,45593.000000,45593.000000,45593.000000
mean,17.017729,70.231332,17.465186,70.845702,1.023359
std,8.185109,22.883647,7.335122,21.118812,0.839065
min,-30.905562,-88.366217,0.010000,0.010000,0.000000
25%,12.933284,73.170000,12.988453,73.280000,0.000000
50%,18.546947,75.898497,18.633934,76.002574,1.000000
75%,22.728163,78.044095,22.785049,78.107044,2.000000
max,30.914057,88.433452,31.054057,88.563452,3.000000

In [1616]:
dataset.isnull().sum()

ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Date                     0
Time_Orderd                    0
Time_Order_picked              0
Weatherconditions              0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken(min)                0
dtype: int64

In [1617]:
dataset.duplicated().sum()

np.int64(0)

In [1618]:
for col in dataset.select_dtypes(include=['string']).columns:
    dataset[col] = dataset[col].astype(str).str.replace(' ', '', regex=False)

In [1619]:
dataset.duplicated().sum()

np.int64(0)

In [1620]:
dataset['Delivery_person_Age'].value_counts()

Delivery_person_Age
35     2262
36     2260
37     2227
30     2226
38     2219
24     2210
32     2202
22     2196
29     2191
33     2187
28     2179
25     2174
34     2166
26     2159
21     2153
27     2150
39     2144
20     2136
31     2120
23     2087
NaN    1854
50       53
15       38
Name: count, dtype: int64

In [1621]:
dataset['Delivery_person_Age'] = dataset['Delivery_person_Age'].replace('NaN', np.nan )

In [1622]:
dataset['Delivery_person_Age'].value_counts()

Delivery_person_Age
35    2262
36    2260
37    2227
30    2226
38    2219
24    2210
32    2202
22    2196
29    2191
33    2187
28    2179
25    2174
34    2166
26    2159
21    2153
27    2150
39    2144
20    2136
31    2120
23    2087
50      53
15      38
Name: count, dtype: int64

In [1623]:
dataset['Delivery_person_Age'] = dataset['Delivery_person_Age'].astype('Int64')

In [1624]:
dataset['Delivery_person_Age'].mean()

np.float64(29.567136880129862)

In [1625]:
dataset['Delivery_person_Age'].isnull().sum()

np.int64(1854)

In [1626]:
dataset['Delivery_person_Age'] = dataset['Delivery_person_Age'].replace(np.nan,29)

In [1627]:
dataset['Delivery_person_Age'].value_counts()

Delivery_person_Age
29    4045
35    2262
36    2260
37    2227
30    2226
38    2219
24    2210
32    2202
22    2196
33    2187
28    2179
25    2174
34    2166
26    2159
21    2153
27    2150
39    2144
20    2136
31    2120
23    2087
50      53
15      38
Name: count, dtype: Int64

In [1628]:
dataset['Delivery_person_Age'].isnull().sum()

np.int64(0)

In [1629]:
dataset['Delivery_person_Ratings'].value_counts()

Delivery_person_Ratings
4.8    7148
4.7    7142
4.9    7041
4.6    6940
5      3996
4.5    3303
NaN    1908
4.1    1430
4.2    1418
4.3    1409
4.4    1361
4      1077
3.5     249
3.8     228
3.7     225
3.6     207
3.9     197
6        53
1        38
3.4      32
3.1      29
3.2      29
3.3      25
2.6      22
2.7      22
2.5      20
2.8      19
2.9      19
3         6
Name: count, dtype: int64

In [1630]:
dataset['Delivery_person_Ratings'] = dataset['Delivery_person_Ratings'].replace('NaN',np.nan)

In [1631]:
dataset['Delivery_person_Ratings'].isnull().sum()

np.int64(1908)

In [1632]:
dataset['Delivery_person_Ratings'].value_counts()

Delivery_person_Ratings
4.8    7148
4.7    7142
4.9    7041
4.6    6940
5      3996
4.5    3303
4.1    1430
4.2    1418
4.3    1409
4.4    1361
4      1077
3.5     249
3.8     228
3.7     225
3.6     207
3.9     197
6        53
1        38
3.4      32
3.1      29
3.2      29
3.3      25
2.6      22
2.7      22
2.5      20
2.8      19
2.9      19
3         6
Name: count, dtype: int64

In [1633]:
dataset['Delivery_person_Ratings'] = dataset['Delivery_person_Ratings'].astype('float64')

In [1634]:
dataset['Delivery_person_Ratings'].mean()

np.float64(4.633780473846858)

In [1635]:
dataset['Delivery_person_Ratings'] = dataset['Delivery_person_Ratings'].replace(np.nan, 4.6)

In [1636]:
dataset['Delivery_person_Ratings'].value_counts()

Delivery_person_Ratings
4.6    8848
4.8    7148
4.7    7142
4.9    7041
5.0    3996
4.5    3303
4.1    1430
4.2    1418
4.3    1409
4.4    1361
4.0    1077
3.5     249
3.8     228
3.7     225
3.6     207
3.9     197
6.0      53
1.0      38
3.4      32
3.1      29
3.2      29
3.3      25
2.6      22
2.7      22
2.5      20
2.8      19
2.9      19
3.0       6
Name: count, dtype: int64

In [1637]:
dataset['Delivery_person_Ratings'].isnull().sum()

np.int64(0)

In [1638]:
dataset[['Restaurant_latitude', 'Restaurant_longitude']].describe()

       Restaurant_latitude  Restaurant_longitude
count         45593.000000          45593.000000
mean             17.017729             70.231332
std               8.185109             22.883647
min             -30.905562            -88.366217
25%              12.933284             73.170000
50%              18.546947             75.898497
75%              22.728163             78.044095
max              30.914057             88.433452

In [1639]:
coords = [
    'Restaurant_latitude', 
    'Restaurant_longitude', 
    'Delivery_location_latitude', 
    'Delivery_location_longitude'
]

negative_rows = dataset[(dataset[coords] < 0).any(axis=1)]

negative_rows.groupby(coords).size().reset_index(name='count')

,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,count
0,-30.905562,-75.832841,31.045562,75.972841,1
1,-30.902872,75.826808,30.972872,75.896808,1
2,-30.902872,75.826808,31.012872,75.936808,1
3,-30.899584,75.809346,30.929584,75.839346,1
4,-30.899584,75.809346,30.949584,75.859346,1
...,...,...,...,...,...
415,-9.966783,76.242981,10.016783,76.292981,1
416,-9.960846,-76.293936,10.030846,76.363936,1
417,-9.960846,76.293936,10.050846,76.383936,1
418,-9.959778,76.296106,9.969778,76.306106,1
419,-9.959778,76.296106,10.069778,76.406106,1

In [1640]:
dataset['Time_taken(min)'].max()

'(min)54'

In [1641]:
dataset['Restaurant_latitude'] = dataset['Restaurant_latitude'].abs()
dataset['Restaurant_longitude'] = dataset['Restaurant_longitude'].abs()

In [1642]:
(dataset['Restaurant_latitude'] < 1).sum()

np.int64(3640)

In [1643]:
(dataset['Restaurant_longitude'] < 1).sum()

np.int64(3640)

In [1644]:
dataset.loc[dataset['Restaurant_latitude'] < 1,
            ['Restaurant_latitude', 'Restaurant_longitude']] = None

In [1645]:
dataset[['Restaurant_latitude', 'Restaurant_longitude']].isnull().sum()

Restaurant_latitude     3640
Restaurant_longitude    3640
dtype: int64

In [1646]:
dataset[['Delivery_location_latitude', 'Delivery_location_longitude']].describe()

       Delivery_location_latitude  Delivery_location_longitude
count                45593.000000                 45593.000000
mean                    17.465186                    70.845702
std                      7.335122                    21.118812
min                      0.010000                     0.010000
25%                     12.988453                    73.280000
50%                     18.633934                    76.002574
75%                     22.785049                    78.107044
max                     31.054057                    88.563452

In [1647]:
dataset['Order_Date'] = pd.to_datetime(dataset['Order_Date'], dayfirst=True, format='mixed')

In [1648]:
dataset['Order_Date'].dtype

dtype('<M8[us]')

In [1649]:
dataset[['Time_Orderd', 'Time_Order_picked']].head()

  Time_Orderd Time_Order_picked
0    11:30:00          11:45:00
1    19:45:00          19:50:00
2     8:30:00           8:45:00
3    18:00:00          18:10:00
4    13:30:00          13:45:00

In [1650]:
dataset['Weatherconditions'].unique()

<StringArray>
[     'conditionsSunny',     'conditionsStormy', 'conditionsSandstorms',
     'conditionsCloudy',        'conditionsFog',      'conditionsWindy',
        'conditionsNaN']
Length: 7, dtype: str

In [1651]:
dataset['Weatherconditions'] = dataset['Weatherconditions'].str.replace('conditionsNaN', 'unknown')

In [1652]:
dataset['Weatherconditions'].unique()

<StringArray>
[     'conditionsSunny',     'conditionsStormy', 'conditionsSandstorms',
     'conditionsCloudy',        'conditionsFog',      'conditionsWindy',
              'unknown']
Length: 7, dtype: str

In [1653]:
dataset['Road_traffic_density'].unique()

<StringArray>
['High', 'Jam', 'Low', 'Medium', 'NaN']
Length: 5, dtype: str

In [1654]:
dataset['Road_traffic_density'] = dataset['Road_traffic_density'].str.replace('NaN', 'unknown')

In [1655]:
dataset['Road_traffic_density'].unique()

<StringArray>
['High', 'Jam', 'Low', 'Medium', 'unknown']
Length: 5, dtype: str

In [1656]:
dataset['Vehicle_condition'].unique()

array([2, 0, 1, 3])

In [1657]:
dataset['Type_of_order'].unique()

<StringArray>
['Snack', 'Drinks', 'Buffet', 'Meal']
Length: 4, dtype: str

In [1658]:
dataset['Type_of_vehicle'].unique()

<StringArray>
['motorcycle', 'scooter', 'electric_scooter', 'bicycle']
Length: 4, dtype: str

In [1659]:
dataset['multiple_deliveries'].value_counts()

multiple_deliveries
1      28159
0      14095
2       1985
NaN      993
3        361
Name: count, dtype: int64

In [1660]:
dataset['multiple_deliveries'] = dataset['multiple_deliveries'].str.replace('NaN', '1')
dataset['multiple_deliveries'] = dataset['multiple_deliveries'].astype('int64')

In [1661]:
dataset['multiple_deliveries'].value_counts()

multiple_deliveries
1    29152
0    14095
2     1985
3      361
Name: count, dtype: int64

In [1662]:
dataset['Festival'].unique()

<StringArray>
['No', 'Yes', 'NaN']
Length: 3, dtype: str

In [1663]:
dataset['Festival'] = dataset['Festival'].str.replace('NaN', 'unknown')

In [1664]:
dataset['Festival'].unique()

<StringArray>
['No', 'Yes', 'unknown']
Length: 3, dtype: str

In [1665]:
dataset['City'].value_counts()

City
Metropolitian    34093
Urban            10136
NaN               1200
Semi-Urban         164
Name: count, dtype: int64

In [1666]:
dataset['City'] = dataset['City'].str.replace('NaN', 'unknown')

In [1667]:
dataset['City'].value_counts()

City
Metropolitian    34093
Urban            10136
unknown           1200
Semi-Urban         164
Name: count, dtype: int64

In [1668]:
dataset['Time_taken(min)'].head()

0    (min)24
1    (min)33
2    (min)26
3    (min)21
4    (min)30
Name: Time_taken(min), dtype: str

In [1669]:
dataset['Time_taken(min)'] = dataset['Time_taken(min)'].str.replace('(min)', ' ').str.strip()
dataset['Time_taken(min)'] = dataset['Time_taken(min)'].astype('int64')

In [1670]:
dataset['Time_taken(min)'].head()

0    24
1    33
2    26
3    21
4    30
Name: Time_taken(min), dtype: int64

In [1671]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  str
 1   Delivery_person_ID           45593 non-null  str
 2   Delivery_person_Age          45593 non-null  Int64
 3   Delivery_person_Ratings      45593 non-null  float64
 4   Restaurant_latitude          41953 non-null  float64
 5   Restaurant_longitude         41953 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Order_Date                   45593 non-null  datetime64[us]
 9   Time_Orderd                  45593 non-null  str
 10  Time_Order_picked            45593 non-null  str
 11  Weatherconditions            45593 non-null  str
 12  Road_traffic_density         45593 non-null  str
 13  Vehicle_condition            45593 non-null  int64
 14  Type_of_order                45593 non-null  str
 15  Type_of_vehicle              45593 non-null  str
 16  multiple_deliveries          45593 non-null  int64
 17  Festival                     45593 non-null  str
 18  City                         45593 non-null  str
 19  Time_taken(min)              45593 non-null  int64
dtypes: Int64(1), datetime64[us](1), float64(5), int64(3), str(10)
memory usage: 7.0 MB

In [1672]:
dataset.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age               0
Delivery_person_Ratings           0
Restaurant_latitude            3640
Restaurant_longitude           3640
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                       0
Time_Order_picked                 0
Weatherconditions                 0
Road_traffic_density              0
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries               0
Festival                          0
City                              0
Time_taken(min)                   0
dtype: int64

In [1673]:
dataset.to_csv('train_cleaned.csv', index=False)